#!/bin/sh

# wrap-for-bin.sh: Template for git executable wrapper scripts
# to run test suite against sandbox, but with only bindir-installed
# executables in PATH.  The Makefile copies this into various
# files in bin-wrappers, substituting
# /git_test/git-2.9.5 and t/helper/test-sigchain.

GIT_EXEC_PATH='/git_test/git-2.9.5'
if test -n "$NO_SET_GIT_TEMPLATE_DIR"
then
	unset GIT_TEMPLATE_DIR
else
	GIT_TEMPLATE_DIR='/git_test/git-2.9.5/templates/blt'
	export GIT_TEMPLATE_DIR
fi
GITPERLLIB='/git_test/git-2.9.5/perl/blib/lib'"${GITPERLLIB:+:$GITPERLLIB}"
GIT_TEXTDOMAINDIR='/git_test/git-2.9.5/po/build/locale'
PATH='/git_test/git-2.9.5/bin-wrappers:'"$PATH"

export GIT_EXEC_PATH GITPERLLIB PATH GIT_TEXTDOMAINDIR

if test -n "$GIT_TEST_GDB"
then
	unset GIT_TEST_GDB
	exec gdb --args "${GIT_EXEC_PATH}/t/helper/test-sigchain" "$@"
else
	exec "${GIT_EXEC_PATH}/t/helper/test-sigchain" "$@"
fi
